name: Deploy Secrets

on: [push, pull_request]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Firebase key
        env:
          FIREBASE_KEY: ${{ secrets.FIREBASE_KEY }}
        run: |
          mkdir -p ~/src/key
          echo "$FIREBASE_KEY" > ~/src/key/plant-analysis-key.json